<?php

namespace Database\Seeders;

use App\Models\GeoPoliticalZone;
use App\Models\Lga;
use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->allGeoPoliticalZones() as $geo_political_zone) {
            GeoPoliticalZone::updateOrCreate($geo_political_zone);
        }

        foreach ($this->allStates() as $state) {
            State::updateOrCreate($state);
        }

        foreach ($this->allStateLGA() as $lga) {
            Lga::updateOrCreate($lga);
        }
    }

    private function allGeoPoliticalZones()
    {
        return  array(
            array('id' => 1, 'geo_political_zone_name' => 'North Central'),
            array('id' => 2, 'geo_political_zone_name' => 'North East'),
            array('id' => 3, 'geo_political_zone_name' => 'North West'),
            array('id' => 4, 'geo_political_zone_name' => 'South East'),
            array('id' => 5, 'geo_political_zone_name' => 'South South'),
            array('id' => 6, 'geo_political_zone_name' => 'South West'),
        );
    }

    private function allStates()
    {
        return $state = array(
            array('id' => 1, 'state_name' => 'Anambra', 'geo_political_zone_id' => 4),
            array('id' => 2, 'state_name' => 'Enugu', 'geo_political_zone_id' => 4),
            array('id' => 3, 'state_name' => 'Akwa Ibom', 'geo_political_zone_id' => 5),
            array('id' => 4, 'state_name' => 'Adamawa', 'geo_political_zone_id' => 2),
            array('id' => 5, 'state_name' => 'Abia', 'geo_political_zone_id' => 4),
            array('id' => 6, 'state_name' => 'Bauchi', 'geo_political_zone_id' => 2),
            array('id' => 7, 'state_name' => 'Bayelsa', 'geo_political_zone_id' => 5),
            array('id' => 8, 'state_name' => 'Benue', 'geo_political_zone_id' => 1),
            array('id' => 9, 'state_name' => 'Borno', 'geo_political_zone_id' => 2),
            array('id' => 10, 'state_name' => 'Cross River', 'geo_political_zone_id' => 5),
            array('id' => 11, 'state_name' => 'Delta', 'geo_political_zone_id' => 5),
            array('id' => 12, 'state_name' => 'Ebonyi', 'geo_political_zone_id' => 4),
            array('id' => 13, 'state_name' => 'Edo', 'geo_political_zone_id' => 5),
            array('id' => 14, 'state_name' => 'Ekiti', 'geo_political_zone_id' => 6),
            array('id' => 15, 'state_name' => 'Gombe', 'geo_political_zone_id' => 2),
            array('id' => 16, 'state_name' => 'Imo', 'geo_political_zone_id' => 4),
            array('id' => 17, 'state_name' => 'Jigawa', 'geo_political_zone_id' => 3),
            array('id' => 18, 'state_name' => 'Kaduna', 'geo_political_zone_id' => 3),
            array('id' => 19, 'state_name' => 'Kano', 'geo_political_zone_id' => 3),
            array('id' => 20, 'state_name' => 'Katsina', 'geo_political_zone_id' => 3),
            array('id' => 21, 'state_name' => 'Kebbi', 'geo_political_zone_id' => 3),
            array('id' => 22, 'state_name' => 'Kogi', 'geo_political_zone_id' => 1),
            array('id' => 23, 'state_name' => 'Kwara', 'geo_political_zone_id' => 1),
            array('id' => 24, 'state_name' => 'Lagos', 'geo_political_zone_id' => 6),
            array('id' => 25, 'state_name' => 'Nasarawa', 'geo_political_zone_id' => 1),
            array('id' => 26, 'state_name' => 'Niger', 'geo_political_zone_id' => 1),
            array('id' => 27, 'state_name' => 'Ogun', 'geo_political_zone_id' => 6),
            array('id' => 28, 'state_name' => 'Ondo', 'geo_political_zone_id' => 6),
            array('id' => 29, 'state_name' => 'Osun', 'geo_political_zone_id' => 6),
            array('id' => 30, 'state_name' => 'Oyo', 'geo_political_zone_id' => 6),
            array('id' => 31, 'state_name' => 'Plateau', 'geo_political_zone_id' => 1),
            array('id' => 32, 'state_name' => 'Rivers', 'geo_political_zone_id' => 5),
            array('id' => 33, 'state_name' => 'Sokoto', 'geo_political_zone_id' => 3),
            array('id' => 34, 'state_name' => 'Taraba', 'geo_political_zone_id' => 2),
            array('id' => 35, 'state_name' => 'Yobe', 'geo_political_zone_id' => 2),
            array('id' => 36, 'state_name' => 'Zamfara', 'geo_political_zone_id' => 3),
            array('id' => 38, 'state_name' => 'F.C.T', 'geo_political_zone_id' => 1)
        );
    }

    private function allStateLGA()
    {
        return $state_lga = array(
            array('id' => 1, 'state_id' => 5, 'lga_name' => 'Aba North'),
            array('id' => 2, 'state_id' => 5, 'lga_name' => 'Aba South'),
            array('id' => 3, 'state_id' => 5, 'lga_name' => 'Arochukwu'),
            array('id' => 4, 'state_id' => 5, 'lga_name' => 'Bende'),
            array('id' => 5, 'state_id' => 5, 'lga_name' => 'Ikwuano'),
            array('id' => 6, 'state_id' => 5, 'lga_name' => 'Isiala Ngwa North'),
            array('id' => 7, 'state_id' => 5, 'lga_name' => 'Isiala Ngwa South'),
            array('id' => 8, 'state_id' => 5, 'lga_name' => 'Isuikwuato'),
            array('id' => 9, 'state_id' => 5, 'lga_name' => 'Obi Ngwa'),
            array('id' => 10, 'state_id' => 5, 'lga_name' => 'Ohafia'),
            array('id' => 11, 'state_id' => 5, 'lga_name' => 'Osisioma'),
            array('id' => 12, 'state_id' => 5, 'lga_name' => 'Ugwunagbo'),
            array('id' => 13, 'state_id' => 5, 'lga_name' => 'Ukwa East'),
            array('id' => 14, 'state_id' => 5, 'lga_name' => 'Ukwa West'),
            array('id' => 15, 'state_id' => 5, 'lga_name' => 'Umuahia North'),
            array('id' => 16, 'state_id' => 5, 'lga_name' => 'Umuahia South'),
            array('id' => 17, 'state_id' => 5, 'lga_name' => 'Umu Nneochi'),
            array('id' => 18, 'state_id' => 4, 'lga_name' => 'Demsa'),
            array('id' => 19, 'state_id' => 4, 'lga_name' => 'Fufure'),
            array('id' => 20, 'state_id' => 4, 'lga_name' => 'Ganye'),
            array('id' => 21, 'state_id' => 4, 'lga_name' => 'Gayuk'),
            array('id' => 22, 'state_id' => 4, 'lga_name' => 'Gombi'),
            array('id' => 23, 'state_id' => 4, 'lga_name' => 'Grie'),
            array('id' => 24, 'state_id' => 4, 'lga_name' => 'Hong'),
            array('id' => 25, 'state_id' => 4, 'lga_name' => 'Jada'),
            array('id' => 26, 'state_id' => 4, 'lga_name' => 'Larmurde'),
            array('id' => 27, 'state_id' => 4, 'lga_name' => 'Madagali'),
            array('id' => 28, 'state_id' => 4, 'lga_name' => 'Maiha'),
            array('id' => 29, 'state_id' => 4, 'lga_name' => 'Mayo Belwa'),
            array('id' => 30, 'state_id' => 4, 'lga_name' => 'Michika'),
            array('id' => 31, 'state_id' => 4, 'lga_name' => 'Mubi North'),
            array('id' => 32, 'state_id' => 4, 'lga_name' => 'Mubi South'),
            array('id' => 33, 'state_id' => 4, 'lga_name' => 'Numan'),
            array('id' => 34, 'state_id' => 4, 'lga_name' => 'Shelleng'),
            array('id' => 35, 'state_id' => 4, 'lga_name' => 'Song'),
            array('id' => 36, 'state_id' => 4, 'lga_name' => 'Toungo'),
            array('id' => 37, 'state_id' => 4, 'lga_name' => 'Yola North'),
            array('id' => 38, 'state_id' => 4, 'lga_name' => 'Yola South'),
            array('id' => 39, 'state_id' => 3, 'lga_name' => 'Abak'),
            array('id' => 40, 'state_id' => 3, 'lga_name' => 'Eastern Obolo'),
            array('id' => 41, 'state_id' => 3, 'lga_name' => 'Eket'),
            array('id' => 42, 'state_id' => 3, 'lga_name' => 'Esit Eket'),
            array('id' => 43, 'state_id' => 3, 'lga_name' => 'Essien Udim'),
            array('id' => 44, 'state_id' => 3, 'lga_name' => 'Etim Ekpo'),
            array('id' => 45, 'state_id' => 3, 'lga_name' => 'Etinan'),
            array('id' => 46, 'state_id' => 3, 'lga_name' => 'Ibeno'),
            array('id' => 47, 'state_id' => 3, 'lga_name' => 'Ibesikpo Asutan'),
            array('id' => 48, 'state_id' => 3, 'lga_name' => 'Ibiono-Ibom'),
            array('id' => 49, 'state_id' => 3, 'lga_name' => 'Ika'),
            array('id' => 50, 'state_id' => 3, 'lga_name' => 'Ikono'),
            array('id' => 51, 'state_id' => 3, 'lga_name' => 'Ikot Abasi'),
            array('id' => 52, 'state_id' => 3, 'lga_name' => 'Ikot Ekpene'),
            array('id' => 53, 'state_id' => 3, 'lga_name' => 'Ini'),
            array('id' => 54, 'state_id' => 3, 'lga_name' => 'Itu'),
            array('id' => 55, 'state_id' => 3, 'lga_name' => 'Mbo'),
            array('id' => 56, 'state_id' => 3, 'lga_name' => 'Mkpat-Enin'),
            array('id' => 57, 'state_id' => 3, 'lga_name' => 'Nsit-Atai'),
            array('id' => 58, 'state_id' => 3, 'lga_name' => 'Nsit-Ibom'),
            array('id' => 59, 'state_id' => 3, 'lga_name' => 'Nsit-Ubium'),
            array('id' => 60, 'state_id' => 3, 'lga_name' => 'Obot Akara'),
            array('id' => 61, 'state_id' => 3, 'lga_name' => 'Okobo'),
            array('id' => 62, 'state_id' => 3, 'lga_name' => 'Onna'),
            array('id' => 63, 'state_id' => 3, 'lga_name' => 'Oron'),
            array('id' => 64, 'state_id' => 3, 'lga_name' => 'Oruk Anam'),
            array('id' => 65, 'state_id' => 3, 'lga_name' => 'Udung-Uko'),
            array('id' => 66, 'state_id' => 3, 'lga_name' => 'Ukanafun'),
            array('id' => 67, 'state_id' => 3, 'lga_name' => 'Uruan'),
            array('id' => 68, 'state_id' => 3, 'lga_name' => 'Urue-Offong/Oruko'),
            array('id' => 69, 'state_id' => 3, 'lga_name' => 'Uyo'),
            array('id' => 70, 'state_id' => 1, 'lga_name' => 'Aguata'),
            array('id' => 71, 'state_id' => 1, 'lga_name' => 'Anambra East'),
            array('id' => 72, 'state_id' => 1, 'lga_name' => 'Anambra West'),
            array('id' => 73, 'state_id' => 1, 'lga_name' => 'Anaocha'),
            array('id' => 74, 'state_id' => 1, 'lga_name' => 'Awka North'),
            array('id' => 75, 'state_id' => 1, 'lga_name' => 'Awka South'),
            array('id' => 76, 'state_id' => 1, 'lga_name' => 'Ayamelum'),
            array('id' => 77, 'state_id' => 1, 'lga_name' => 'Dunukofia'),
            array('id' => 78, 'state_id' => 1, 'lga_name' => 'Ekwusigo'),
            array('id' => 79, 'state_id' => 1, 'lga_name' => 'Idemili North'),
            array('id' => 80, 'state_id' => 1, 'lga_name' => 'Idemili South'),
            array('id' => 81, 'state_id' => 1, 'lga_name' => 'Ihiala'),
            array('id' => 82, 'state_id' => 1, 'lga_name' => 'Njikoka'),
            array('id' => 83, 'state_id' => 1, 'lga_name' => 'Nnewi North'),
            array('id' => 84, 'state_id' => 1, 'lga_name' => 'Nnewi South'),
            array('id' => 85, 'state_id' => 1, 'lga_name' => 'Ogbaru'),
            array('id' => 86, 'state_id' => 1, 'lga_name' => 'Onitsha North'),
            array('id' => 87, 'state_id' => 1, 'lga_name' => 'Onitsha South'),
            array('id' => 88, 'state_id' => 1, 'lga_name' => 'Orumba North'),
            array('id' => 89, 'state_id' => 1, 'lga_name' => 'Orumba South'),
            array('id' => 90, 'state_id' => 1, 'lga_name' => 'Oyi'),
            array('id' => 91, 'state_id' => 6, 'lga_name' => 'Alkaleri'),
            array('id' => 92, 'state_id' => 6, 'lga_name' => 'Bauchi'),
            array('id' => 93, 'state_id' => 6, 'lga_name' => 'Bogoro'),
            array('id' => 94, 'state_id' => 6, 'lga_name' => 'Damban'),
            array('id' => 95, 'state_id' => 6, 'lga_name' => 'Darazo'),
            array('id' => 96, 'state_id' => 6, 'lga_name' => 'Dass'),
            array('id' => 97, 'state_id' => 6, 'lga_name' => 'Gamawa'),
            array('id' => 98, 'state_id' => 6, 'lga_name' => 'Ganjuwa'),
            array('id' => 99, 'state_id' => 6, 'lga_name' => 'Giade'),
            array('id' => 100, 'state_id' => 6, 'lga_name' => 'Itas/Gadau'),
            array('id' => 101, 'state_id' => 6, 'lga_name' => 'Jama\'are'),
            array('id' => 102, 'state_id' => 6, 'lga_name' => 'Katagum'),
            array('id' => 103, 'state_id' => 6, 'lga_name' => 'Kirfi'),
            array('id' => 104, 'state_id' => 6, 'lga_name' => 'Misau'),
            array('id' => 105, 'state_id' => 6, 'lga_name' => 'Ningi'),
            array('id' => 106, 'state_id' => 6, 'lga_name' => 'Shira'),
            array('id' => 107, 'state_id' => 6, 'lga_name' => 'Tafawa Balewa'),
            array('id' => 108, 'state_id' => 6, 'lga_name' => 'Toro'),
            array('id' => 109, 'state_id' => 6, 'lga_name' => 'Warji'),
            array('id' => 110, 'state_id' => 6, 'lga_name' => 'Zaki'),
            array('id' => 111, 'state_id' => 7, 'lga_name' => 'Brass'),
            array('id' => 112, 'state_id' => 7, 'lga_name' => 'Ekeremor'),
            array('id' => 113, 'state_id' => 7, 'lga_name' => 'Kolokuma/Opokuma'),
            array('id' => 114, 'state_id' => 7, 'lga_name' => 'Nembe'),
            array('id' => 115, 'state_id' => 7, 'lga_name' => 'Ogbia'),
            array('id' => 116, 'state_id' => 7, 'lga_name' => 'Sagbama'),
            array('id' => 117, 'state_id' => 7, 'lga_name' => 'Southern Ijaw'),
            array('id' => 118, 'state_id' => 7, 'lga_name' => 'Yenagoa'),
            array('id' => 119, 'state_id' => 8, 'lga_name' => 'Agatu'),
            array('id' => 120, 'state_id' => 8, 'lga_name' => 'Apa'),
            array('id' => 121, 'state_id' => 8, 'lga_name' => 'Ado'),
            array('id' => 122, 'state_id' => 8, 'lga_name' => 'Buruku'),
            array('id' => 123, 'state_id' => 8, 'lga_name' => 'Gboko'),
            array('id' => 124, 'state_id' => 8, 'lga_name' => 'Guma'),
            array('id' => 125, 'state_id' => 8, 'lga_name' => 'Gwer East'),
            array('id' => 126, 'state_id' => 8, 'lga_name' => 'Gwer West'),
            array('id' => 127, 'state_id' => 8, 'lga_name' => 'Katsina-Ala'),
            array('id' => 128, 'state_id' => 8, 'lga_name' => 'Konshisha'),
            array('id' => 129, 'state_id' => 8, 'lga_name' => 'Kwande'),
            array('id' => 130, 'state_id' => 8, 'lga_name' => 'Logo'),
            array('id' => 131, 'state_id' => 8, 'lga_name' => 'Makurdi'),
            array('id' => 132, 'state_id' => 8, 'lga_name' => 'Obi'),
            array('id' => 133, 'state_id' => 8, 'lga_name' => 'Ogbadibo'),
            array('id' => 134, 'state_id' => 8, 'lga_name' => 'Ohimini'),
            array('id' => 135, 'state_id' => 8, 'lga_name' => 'Oju'),
            array('id' => 136, 'state_id' => 8, 'lga_name' => 'Okpokwu'),
            array('id' => 137, 'state_id' => 8, 'lga_name' => 'Oturkpo'),
            array('id' => 138, 'state_id' => 8, 'lga_name' => 'Tarka'),
            array('id' => 139, 'state_id' => 8, 'lga_name' => 'Ukum'),
            array('id' => 140, 'state_id' => 8, 'lga_name' => 'Ushongo'),
            array('id' => 141, 'state_id' => 8, 'lga_name' => 'Vandeikya'),
            array('id' => 142, 'state_id' => 9, 'lga_name' => 'Abadam'),
            array('id' => 143, 'state_id' => 9, 'lga_name' => 'Askira/Uba'),
            array('id' => 144, 'state_id' => 9, 'lga_name' => 'Bama'),
            array('id' => 145, 'state_id' => 9, 'lga_name' => 'Bayo'),
            array('id' => 146, 'state_id' => 9, 'lga_name' => 'Biu'),
            array('id' => 147, 'state_id' => 9, 'lga_name' => 'Chibok'),
            array('id' => 148, 'state_id' => 9, 'lga_name' => 'Damboa'),
            array('id' => 149, 'state_id' => 9, 'lga_name' => 'Dikwa'),
            array('id' => 150, 'state_id' => 9, 'lga_name' => 'Gubio'),
            array('id' => 151, 'state_id' => 9, 'lga_name' => 'Guzamala'),
            array('id' => 152, 'state_id' => 9, 'lga_name' => 'Gwoza'),
            array('id' => 153, 'state_id' => 9, 'lga_name' => 'Hawul'),
            array('id' => 154, 'state_id' => 9, 'lga_name' => 'Jere'),
            array('id' => 155, 'state_id' => 9, 'lga_name' => 'Kaga'),
            array('id' => 156, 'state_id' => 9, 'lga_name' => 'Kala/Balge'),
            array('id' => 157, 'state_id' => 9, 'lga_name' => 'Konduga'),
            array('id' => 158, 'state_id' => 9, 'lga_name' => 'Kukawa'),
            array('id' => 159, 'state_id' => 9, 'lga_name' => 'Kwaya Kusar'),
            array('id' => 160, 'state_id' => 9, 'lga_name' => 'Mafa'),
            array('id' => 161, 'state_id' => 9, 'lga_name' => 'Magumeri'),
            array('id' => 162, 'state_id' => 9, 'lga_name' => 'Maiduguri'),
            array('id' => 163, 'state_id' => 9, 'lga_name' => 'Marte'),
            array('id' => 164, 'state_id' => 9, 'lga_name' => 'Mobbar'),
            array('id' => 165, 'state_id' => 9, 'lga_name' => 'Monguno'),
            array('id' => 166, 'state_id' => 9, 'lga_name' => 'Ngala'),
            array('id' => 167, 'state_id' => 9, 'lga_name' => 'Nganzai'),
            array('id' => 168, 'state_id' => 9, 'lga_name' => 'Shani'),
            array('id' => 169, 'state_id' => 10, 'lga_name' => 'Abi'),
            array('id' => 170, 'state_id' => 10, 'lga_name' => 'Akamkpa'),
            array('id' => 171, 'state_id' => 10, 'lga_name' => 'Akpabuyo'),
            array('id' => 172, 'state_id' => 10, 'lga_name' => 'Bakassi'),
            array('id' => 173, 'state_id' => 10, 'lga_name' => 'Bekwarra'),
            array('id' => 174, 'state_id' => 10, 'lga_name' => 'Biase'),
            array('id' => 175, 'state_id' => 10, 'lga_name' => 'Boki'),
            array('id' => 176, 'state_id' => 10, 'lga_name' => 'Calabar Municipal'),
            array('id' => 177, 'state_id' => 10, 'lga_name' => 'Calabar South'),
            array('id' => 178, 'state_id' => 10, 'lga_name' => 'Etung'),
            array('id' => 179, 'state_id' => 10, 'lga_name' => 'Ikom'),
            array('id' => 180, 'state_id' => 10, 'lga_name' => 'Obanliku'),
            array('id' => 181, 'state_id' => 10, 'lga_name' => 'Obubra'),
            array('id' => 182, 'state_id' => 10, 'lga_name' => 'Obudu'),
            array('id' => 183, 'state_id' => 10, 'lga_name' => 'Odukpani'),
            array('id' => 184, 'state_id' => 10, 'lga_name' => 'Ogoja'),
            array('id' => 185, 'state_id' => 10, 'lga_name' => 'Yakuur'),
            array('id' => 186, 'state_id' => 10, 'lga_name' => 'Yala'),
            array('id' => 187, 'state_id' => 11, 'lga_name' => 'Aniocha North'),
            array('id' => 188, 'state_id' => 11, 'lga_name' => 'Aniocha South'),
            array('id' => 189, 'state_id' => 11, 'lga_name' => 'Bomadi'),
            array('id' => 190, 'state_id' => 11, 'lga_name' => 'Burutu'),
            array('id' => 191, 'state_id' => 11, 'lga_name' => 'Ethiope East'),
            array('id' => 192, 'state_id' => 11, 'lga_name' => 'Ethiope West'),
            array('id' => 193, 'state_id' => 11, 'lga_name' => 'Ika North East'),
            array('id' => 194, 'state_id' => 11, 'lga_name' => 'Ika South'),
            array('id' => 195, 'state_id' => 11, 'lga_name' => 'Isoko North'),
            array('id' => 196, 'state_id' => 11, 'lga_name' => 'Isoko South'),
            array('id' => 197, 'state_id' => 11, 'lga_name' => 'Ndokwa East'),
            array('id' => 198, 'state_id' => 11, 'lga_name' => 'Ndokwa West'),
            array('id' => 199, 'state_id' => 11, 'lga_name' => 'Okpe'),
            array('id' => 200, 'state_id' => 11, 'lga_name' => 'Oshimili North'),
            array('id' => 201, 'state_id' => 11, 'lga_name' => 'Oshimili South'),
            array('id' => 202, 'state_id' => 11, 'lga_name' => 'Patani'),
            array('id' => 203, 'state_id' => 11, 'lga_name' => 'Sapele, Delta'),
            array('id' => 204, 'state_id' => 11, 'lga_name' => 'Udu'),
            array('id' => 205, 'state_id' => 11, 'lga_name' => 'Ughelli North'),
            array('id' => 206, 'state_id' => 11, 'lga_name' => 'Ughelli South'),
            array('id' => 207, 'state_id' => 11, 'lga_name' => 'Ukwuani'),
            array('id' => 208, 'state_id' => 11, 'lga_name' => 'Uvwie'),
            array('id' => 209, 'state_id' => 11, 'lga_name' => 'Warri North'),
            array('id' => 210, 'state_id' => 11, 'lga_name' => 'Warri South'),
            array('id' => 211, 'state_id' => 11, 'lga_name' => 'Warri South West'),
            array('id' => 212, 'state_id' => 12, 'lga_name' => 'Abakaliki'),
            array('id' => 213, 'state_id' => 12, 'lga_name' => 'Afikpo North'),
            array('id' => 214, 'state_id' => 12, 'lga_name' => 'Afikpo South'),
            array('id' => 215, 'state_id' => 12, 'lga_name' => 'Ebonyi'),
            array('id' => 216, 'state_id' => 12, 'lga_name' => 'Ezza North'),
            array('id' => 217, 'state_id' => 12, 'lga_name' => 'Ezza South'),
            array('id' => 218, 'state_id' => 12, 'lga_name' => 'Ikwo'),
            array('id' => 219, 'state_id' => 12, 'lga_name' => 'Ishielu'),
            array('id' => 220, 'state_id' => 12, 'lga_name' => 'Ivo'),
            array('id' => 221, 'state_id' => 12, 'lga_name' => 'Izzi'),
            array('id' => 222, 'state_id' => 12, 'lga_name' => 'Ohaozara'),
            array('id' => 223, 'state_id' => 12, 'lga_name' => 'Ohaukwu'),
            array('id' => 224, 'state_id' => 12, 'lga_name' => 'Onicha'),
            array('id' => 225, 'state_id' => 13, 'lga_name' => 'Akoko-Edo'),
            array('id' => 226, 'state_id' => 13, 'lga_name' => 'Egor'),
            array('id' => 227, 'state_id' => 13, 'lga_name' => 'Esan Central'),
            array('id' => 228, 'state_id' => 13, 'lga_name' => 'Esan North-East'),
            array('id' => 229, 'state_id' => 13, 'lga_name' => 'Esan South-East'),
            array('id' => 230, 'state_id' => 13, 'lga_name' => 'Esan West'),
            array('id' => 231, 'state_id' => 13, 'lga_name' => 'Etsako Central'),
            array('id' => 232, 'state_id' => 13, 'lga_name' => 'Etsako East'),
            array('id' => 233, 'state_id' => 13, 'lga_name' => 'Etsako West'),
            array('id' => 234, 'state_id' => 13, 'lga_name' => 'Igueben'),
            array('id' => 235, 'state_id' => 13, 'lga_name' => 'Ikpoba Okha'),
            array('id' => 236, 'state_id' => 13, 'lga_name' => 'Orhionmwon'),
            array('id' => 237, 'state_id' => 13, 'lga_name' => 'Oredo'),
            array('id' => 238, 'state_id' => 13, 'lga_name' => 'Ovia North-East'),
            array('id' => 239, 'state_id' => 13, 'lga_name' => 'Ovia South-West'),
            array('id' => 240, 'state_id' => 13, 'lga_name' => 'Owan East'),
            array('id' => 241, 'state_id' => 13, 'lga_name' => 'Owan West'),
            array('id' => 242, 'state_id' => 13, 'lga_name' => 'Uhunmwonde'),
            array('id' => 243, 'state_id' => 14, 'lga_name' => 'Ado Ekiti'),
            array('id' => 244, 'state_id' => 14, 'lga_name' => 'Efon'),
            array('id' => 245, 'state_id' => 14, 'lga_name' => 'Ekiti East'),
            array('id' => 246, 'state_id' => 14, 'lga_name' => 'Ekiti South-West'),
            array('id' => 247, 'state_id' => 14, 'lga_name' => 'Ekiti West'),
            array('id' => 248, 'state_id' => 14, 'lga_name' => 'Emure'),
            array('id' => 249, 'state_id' => 14, 'lga_name' => 'Gbonyin'),
            array('id' => 250, 'state_id' => 14, 'lga_name' => 'Ido Osi'),
            array('id' => 251, 'state_id' => 14, 'lga_name' => 'Ijero'),
            array('id' => 252, 'state_id' => 14, 'lga_name' => 'Ikere'),
            array('id' => 253, 'state_id' => 14, 'lga_name' => 'Ikole'),
            array('id' => 254, 'state_id' => 14, 'lga_name' => 'Ilejemeje'),
            array('id' => 255, 'state_id' => 14, 'lga_name' => 'Irepodun/Ifelodun'),
            array('id' => 256, 'state_id' => 14, 'lga_name' => 'Ise/Orun'),
            array('id' => 257, 'state_id' => 14, 'lga_name' => 'Moba'),
            array('id' => 258, 'state_id' => 14, 'lga_name' => 'Oye'),
            array('id' => 259, 'state_id' => 2, 'lga_name' => 'Aninri'),
            array('id' => 260, 'state_id' => 2, 'lga_name' => 'Awgu'),
            array('id' => 261, 'state_id' => 2, 'lga_name' => 'Enugu East'),
            array('id' => 262, 'state_id' => 2, 'lga_name' => 'Enugu North'),
            array('id' => 263, 'state_id' => 2, 'lga_name' => 'Enugu South'),
            array('id' => 264, 'state_id' => 2, 'lga_name' => 'Ezeagu'),
            array('id' => 265, 'state_id' => 2, 'lga_name' => 'Igbo Etiti'),
            array('id' => 266, 'state_id' => 2, 'lga_name' => 'Igbo Eze North'),
            array('id' => 267, 'state_id' => 2, 'lga_name' => 'Igbo Eze South'),
            array('id' => 268, 'state_id' => 2, 'lga_name' => 'Isi Uzo'),
            array('id' => 269, 'state_id' => 2, 'lga_name' => 'Nkanu East'),
            array('id' => 270, 'state_id' => 2, 'lga_name' => 'Nkanu West'),
            array('id' => 271, 'state_id' => 2, 'lga_name' => 'Nsukka'),
            array('id' => 272, 'state_id' => 2, 'lga_name' => 'Oji River'),
            array('id' => 273, 'state_id' => 2, 'lga_name' => 'Udenu'),
            array('id' => 274, 'state_id' => 2, 'lga_name' => 'Udi'),
            array('id' => 275, 'state_id' => 2, 'lga_name' => 'Uzo Uwani'),
            array('id' => 276, 'state_id' => 38, 'lga_name' => 'Abaji'),
            array('id' => 277, 'state_id' => 38, 'lga_name' => 'Bwari'),
            array('id' => 278, 'state_id' => 38, 'lga_name' => 'Gwagwalada'),
            array('id' => 279, 'state_id' => 38, 'lga_name' => 'Kuje'),
            array('id' => 280, 'state_id' => 38, 'lga_name' => 'Kwali'),
            array('id' => 281, 'state_id' => 38, 'lga_name' => 'Municipal Area Council'),
            array('id' => 282, 'state_id' => 15, 'lga_name' => 'Akko'),
            array('id' => 283, 'state_id' => 15, 'lga_name' => 'Balanga'),
            array('id' => 284, 'state_id' => 15, 'lga_name' => 'Billiri'),
            array('id' => 285, 'state_id' => 15, 'lga_name' => 'Dukku'),
            array('id' => 286, 'state_id' => 15, 'lga_name' => 'Funakaye'),
            array('id' => 287, 'state_id' => 15, 'lga_name' => 'Gombe'),
            array('id' => 288, 'state_id' => 15, 'lga_name' => 'Kaltungo'),
            array('id' => 289, 'state_id' => 15, 'lga_name' => 'Kwami'),
            array('id' => 290, 'state_id' => 15, 'lga_name' => 'Nafada'),
            array('id' => 291, 'state_id' => 15, 'lga_name' => 'Shongom'),
            array('id' => 292, 'state_id' => 15, 'lga_name' => 'Yamaltu/Deba'),
            array('id' => 293, 'state_id' => 16, 'lga_name' => 'Aboh Mbaise'),
            array('id' => 294, 'state_id' => 16, 'lga_name' => 'Ahiazu Mbaise'),
            array('id' => 295, 'state_id' => 16, 'lga_name' => 'Ehime Mbano'),
            array('id' => 296, 'state_id' => 16, 'lga_name' => 'Ezinihitte'),
            array('id' => 297, 'state_id' => 16, 'lga_name' => 'Ideato North'),
            array('id' => 298, 'state_id' => 16, 'lga_name' => 'Ideato South'),
            array('id' => 299, 'state_id' => 16, 'lga_name' => 'Ihitte/Uboma'),
            array('id' => 300, 'state_id' => 16, 'lga_name' => 'Ikeduru'),
            array('id' => 301, 'state_id' => 16, 'lga_name' => 'Isiala Mbano'),
            array('id' => 302, 'state_id' => 16, 'lga_name' => 'Isu'),
            array('id' => 303, 'state_id' => 16, 'lga_name' => 'Mbaitoli'),
            array('id' => 304, 'state_id' => 16, 'lga_name' => 'Ngor Okpala'),
            array('id' => 305, 'state_id' => 16, 'lga_name' => 'Njaba'),
            array('id' => 306, 'state_id' => 16, 'lga_name' => 'Nkwerre'),
            array('id' => 307, 'state_id' => 16, 'lga_name' => 'Nwangele'),
            array('id' => 308, 'state_id' => 16, 'lga_name' => 'Obowo'),
            array('id' => 309, 'state_id' => 16, 'lga_name' => 'Oguta'),
            array('id' => 310, 'state_id' => 16, 'lga_name' => 'Ohaji/Egbema'),
            array('id' => 311, 'state_id' => 16, 'lga_name' => 'Okigwe'),
            array('id' => 312, 'state_id' => 16, 'lga_name' => 'Orlu'),
            array('id' => 313, 'state_id' => 16, 'lga_name' => 'Orsu'),
            array('id' => 314, 'state_id' => 16, 'lga_name' => 'Oru East'),
            array('id' => 315, 'state_id' => 16, 'lga_name' => 'Oru West'),
            array('id' => 316, 'state_id' => 16, 'lga_name' => 'Owerri Municipal'),
            array('id' => 317, 'state_id' => 16, 'lga_name' => 'Owerri North'),
            array('id' => 318, 'state_id' => 16, 'lga_name' => 'Owerri West'),
            array('id' => 319, 'state_id' => 16, 'lga_name' => 'Unuimo'),
            array('id' => 320, 'state_id' => 17, 'lga_name' => 'Auyo'),
            array('id' => 321, 'state_id' => 17, 'lga_name' => 'Babura'),
            array('id' => 322, 'state_id' => 17, 'lga_name' => 'Biriniwa'),
            array('id' => 323, 'state_id' => 17, 'lga_name' => 'Birnin Kudu'),
            array('id' => 324, 'state_id' => 17, 'lga_name' => 'Buji'),
            array('id' => 325, 'state_id' => 17, 'lga_name' => 'Dutse'),
            array('id' => 326, 'state_id' => 17, 'lga_name' => 'Gagarawa'),
            array('id' => 327, 'state_id' => 17, 'lga_name' => 'Garki'),
            array('id' => 328, 'state_id' => 17, 'lga_name' => 'Gumel'),
            array('id' => 329, 'state_id' => 17, 'lga_name' => 'Guri'),
            array('id' => 330, 'state_id' => 17, 'lga_name' => 'Gwaram'),
            array('id' => 331, 'state_id' => 17, 'lga_name' => 'Gwiwa'),
            array('id' => 332, 'state_id' => 17, 'lga_name' => 'Hadejia'),
            array('id' => 333, 'state_id' => 17, 'lga_name' => 'Jahun'),
            array('id' => 334, 'state_id' => 17, 'lga_name' => 'Kafin Hausa'),
            array('id' => 335, 'state_id' => 17, 'lga_name' => 'Kazaure'),
            array('id' => 336, 'state_id' => 17, 'lga_name' => 'Kiri Kasama'),
            array('id' => 337, 'state_id' => 17, 'lga_name' => 'Kiyawa'),
            array('id' => 338, 'state_id' => 17, 'lga_name' => 'Kaugama'),
            array('id' => 339, 'state_id' => 17, 'lga_name' => 'Maigatari'),
            array('id' => 340, 'state_id' => 17, 'lga_name' => 'Malam Madori'),
            array('id' => 341, 'state_id' => 17, 'lga_name' => 'Miga'),
            array('id' => 342, 'state_id' => 17, 'lga_name' => 'Ringim'),
            array('id' => 343, 'state_id' => 17, 'lga_name' => 'Roni'),
            array('id' => 344, 'state_id' => 17, 'lga_name' => 'Sule Tankarkar'),
            array('id' => 345, 'state_id' => 17, 'lga_name' => 'Taura'),
            array('id' => 346, 'state_id' => 17, 'lga_name' => 'Yankwashi'),
            array('id' => 347, 'state_id' => 18, 'lga_name' => 'Birnin Gwari'),
            array('id' => 348, 'state_id' => 18, 'lga_name' => 'Chikun'),
            array('id' => 349, 'state_id' => 18, 'lga_name' => 'Giwa'),
            array('id' => 350, 'state_id' => 18, 'lga_name' => 'Igabi'),
            array('id' => 351, 'state_id' => 18, 'lga_name' => 'Ikara'),
            array('id' => 352, 'state_id' => 18, 'lga_name' => 'Jaba'),
            array('id' => 353, 'state_id' => 18, 'lga_name' => 'Jema\'a'),
            array('id' => 354, 'state_id' => 18, 'lga_name' => 'Kachia'),
            array('id' => 355, 'state_id' => 18, 'lga_name' => 'Kaduna North'),
            array('id' => 356, 'state_id' => 18, 'lga_name' => 'Kaduna South'),
            array('id' => 357, 'state_id' => 18, 'lga_name' => 'Kagarko'),
            array('id' => 358, 'state_id' => 18, 'lga_name' => 'Kajuru'),
            array('id' => 359, 'state_id' => 18, 'lga_name' => 'Kaura'),
            array('id' => 360, 'state_id' => 18, 'lga_name' => 'Kauru'),
            array('id' => 361, 'state_id' => 18, 'lga_name' => 'Kubau'),
            array('id' => 362, 'state_id' => 18, 'lga_name' => 'Kudan'),
            array('id' => 363, 'state_id' => 18, 'lga_name' => 'Lere'),
            array('id' => 364, 'state_id' => 18, 'lga_name' => 'Makarfi'),
            array('id' => 365, 'state_id' => 18, 'lga_name' => 'Sabon Gari'),
            array('id' => 366, 'state_id' => 18, 'lga_name' => 'Sanga'),
            array('id' => 367, 'state_id' => 18, 'lga_name' => 'Soba'),
            array('id' => 368, 'state_id' => 18, 'lga_name' => 'Zangon Kataf'),
            array('id' => 369, 'state_id' => 18, 'lga_name' => 'Zaria'),
            array('id' => 370, 'state_id' => 19, 'lga_name' => 'Ajingi'),
            array('id' => 371, 'state_id' => 19, 'lga_name' => 'Albasu'),
            array('id' => 372, 'state_id' => 19, 'lga_name' => 'Bagwai'),
            array('id' => 373, 'state_id' => 19, 'lga_name' => 'Bebeji'),
            array('id' => 374, 'state_id' => 19, 'lga_name' => 'Bichi'),
            array('id' => 375, 'state_id' => 19, 'lga_name' => 'Bunkure'),
            array('id' => 376, 'state_id' => 19, 'lga_name' => 'Dala'),
            array('id' => 377, 'state_id' => 19, 'lga_name' => 'Dambatta'),
            array('id' => 378, 'state_id' => 19, 'lga_name' => 'Dawakin Kudu'),
            array('id' => 379, 'state_id' => 19, 'lga_name' => 'Dawakin Tofa'),
            array('id' => 380, 'state_id' => 19, 'lga_name' => 'Doguwa'),
            array('id' => 381, 'state_id' => 19, 'lga_name' => 'Fagge'),
            array('id' => 382, 'state_id' => 19, 'lga_name' => 'Gabasawa'),
            array('id' => 383, 'state_id' => 19, 'lga_name' => 'Garko'),
            array('id' => 384, 'state_id' => 19, 'lga_name' => 'Garun Mallam'),
            array('id' => 385, 'state_id' => 19, 'lga_name' => 'Gaya'),
            array('id' => 386, 'state_id' => 19, 'lga_name' => 'Gezawa'),
            array('id' => 387, 'state_id' => 19, 'lga_name' => 'Gwale'),
            array('id' => 388, 'state_id' => 19, 'lga_name' => 'Gwarzo'),
            array('id' => 389, 'state_id' => 19, 'lga_name' => 'Kabo'),
            array('id' => 390, 'state_id' => 19, 'lga_name' => 'Kano Municipal'),
            array('id' => 391, 'state_id' => 19, 'lga_name' => 'Karaye'),
            array('id' => 392, 'state_id' => 19, 'lga_name' => 'Kibiya'),
            array('id' => 393, 'state_id' => 19, 'lga_name' => 'Kiru'),
            array('id' => 394, 'state_id' => 19, 'lga_name' => 'Kumbotso'),
            array('id' => 395, 'state_id' => 19, 'lga_name' => 'Kunchi'),
            array('id' => 396, 'state_id' => 19, 'lga_name' => 'Kura'),
            array('id' => 397, 'state_id' => 19, 'lga_name' => 'Madobi'),
            array('id' => 398, 'state_id' => 19, 'lga_name' => 'Makoda'),
            array('id' => 399, 'state_id' => 19, 'lga_name' => 'Minjibir'),
            array('id' => 400, 'state_id' => 19, 'lga_name' => 'Nasarawa'),
            array('id' => 401, 'state_id' => 19, 'lga_name' => 'Rano'),
            array('id' => 402, 'state_id' => 19, 'lga_name' => 'Rimin Gado'),
            array('id' => 403, 'state_id' => 19, 'lga_name' => 'Rogo'),
            array('id' => 404, 'state_id' => 19, 'lga_name' => 'Shanono'),
            array('id' => 405, 'state_id' => 19, 'lga_name' => 'Sumaila'),
            array('id' => 406, 'state_id' => 19, 'lga_name' => 'Takai'),
            array('id' => 407, 'state_id' => 19, 'lga_name' => 'Tarauni'),
            array('id' => 408, 'state_id' => 19, 'lga_name' => 'Tofa'),
            array('id' => 409, 'state_id' => 19, 'lga_name' => 'Tsanyawa'),
            array('id' => 410, 'state_id' => 19, 'lga_name' => 'Tudun Wada'),
            array('id' => 411, 'state_id' => 19, 'lga_name' => 'Ungogo'),
            array('id' => 412, 'state_id' => 19, 'lga_name' => 'Warawa'),
            array('id' => 413, 'state_id' => 19, 'lga_name' => 'Wudil'),
            array('id' => 414, 'state_id' => 20, 'lga_name' => 'Bakori'),
            array('id' => 415, 'state_id' => 20, 'lga_name' => 'Batagarawa'),
            array('id' => 416, 'state_id' => 20, 'lga_name' => 'Batsari'),
            array('id' => 417, 'state_id' => 20, 'lga_name' => 'Baure'),
            array('id' => 418, 'state_id' => 20, 'lga_name' => 'Bindawa'),
            array('id' => 419, 'state_id' => 20, 'lga_name' => 'Charanchi'),
            array('id' => 420, 'state_id' => 20, 'lga_name' => 'Dandume'),
            array('id' => 421, 'state_id' => 20, 'lga_name' => 'Danja'),
            array('id' => 422, 'state_id' => 20, 'lga_name' => 'Dan Musa'),
            array('id' => 423, 'state_id' => 20, 'lga_name' => 'Daura'),
            array('id' => 424, 'state_id' => 20, 'lga_name' => 'Dutsi'),
            array('id' => 425, 'state_id' => 20, 'lga_name' => 'Dutsin Ma'),
            array('id' => 426, 'state_id' => 20, 'lga_name' => 'Faskari'),
            array('id' => 427, 'state_id' => 20, 'lga_name' => 'Funtua'),
            array('id' => 428, 'state_id' => 20, 'lga_name' => 'Ingawa'),
            array('id' => 429, 'state_id' => 20, 'lga_name' => 'Jibia'),
            array('id' => 430, 'state_id' => 20, 'lga_name' => 'Kafur'),
            array('id' => 431, 'state_id' => 20, 'lga_name' => 'Kaita'),
            array('id' => 432, 'state_id' => 20, 'lga_name' => 'Kankara'),
            array('id' => 433, 'state_id' => 20, 'lga_name' => 'Kankia'),
            array('id' => 434, 'state_id' => 20, 'lga_name' => 'Katsina'),
            array('id' => 435, 'state_id' => 20, 'lga_name' => 'Kurfi'),
            array('id' => 436, 'state_id' => 20, 'lga_name' => 'Kusada'),
            array('id' => 437, 'state_id' => 20, 'lga_name' => 'Mai\'Adua'),
            array('id' => 438, 'state_id' => 20, 'lga_name' => 'Malumfashi'),
            array('id' => 439, 'state_id' => 20, 'lga_name' => 'Mani'),
            array('id' => 440, 'state_id' => 20, 'lga_name' => 'Mashi'),
            array('id' => 441, 'state_id' => 20, 'lga_name' => 'Matazu'),
            array('id' => 442, 'state_id' => 20, 'lga_name' => 'Musawa'),
            array('id' => 443, 'state_id' => 20, 'lga_name' => 'Rimi'),
            array('id' => 444, 'state_id' => 20, 'lga_name' => 'Sabuwa'),
            array('id' => 445, 'state_id' => 20, 'lga_name' => 'Safana'),
            array('id' => 446, 'state_id' => 20, 'lga_name' => 'Sandamu'),
            array('id' => 447, 'state_id' => 20, 'lga_name' => 'Zango'),
            array('id' => 448, 'state_id' => 21, 'lga_name' => 'Aleiro'),
            array('id' => 449, 'state_id' => 21, 'lga_name' => 'Arewa Dandi'),
            array('id' => 450, 'state_id' => 21, 'lga_name' => 'Argungu'),
            array('id' => 451, 'state_id' => 21, 'lga_name' => 'Augie'),
            array('id' => 452, 'state_id' => 21, 'lga_name' => 'Bagudo'),
            array('id' => 453, 'state_id' => 21, 'lga_name' => 'Birnin Kebbi'),
            array('id' => 454, 'state_id' => 21, 'lga_name' => 'Bunza'),
            array('id' => 455, 'state_id' => 21, 'lga_name' => 'Dandi'),
            array('id' => 456, 'state_id' => 21, 'lga_name' => 'Fakai'),
            array('id' => 457, 'state_id' => 21, 'lga_name' => 'Gwandu'),
            array('id' => 458, 'state_id' => 21, 'lga_name' => 'Jega'),
            array('id' => 459, 'state_id' => 21, 'lga_name' => 'Kalgo'),
            array('id' => 460, 'state_id' => 21, 'lga_name' => 'Koko/Besse'),
            array('id' => 461, 'state_id' => 21, 'lga_name' => 'Maiyama'),
            array('id' => 462, 'state_id' => 21, 'lga_name' => 'Ngaski'),
            array('id' => 463, 'state_id' => 21, 'lga_name' => 'Sakaba'),
            array('id' => 464, 'state_id' => 21, 'lga_name' => 'Shanga'),
            array('id' => 465, 'state_id' => 21, 'lga_name' => 'Suru'),
            array('id' => 466, 'state_id' => 21, 'lga_name' => 'Wasagu/Danko'),
            array('id' => 467, 'state_id' => 21, 'lga_name' => 'Yauri'),
            array('id' => 468, 'state_id' => 21, 'lga_name' => 'Zuru'),
            array('id' => 469, 'state_id' => 22, 'lga_name' => 'Adavi'),
            array('id' => 470, 'state_id' => 22, 'lga_name' => 'Ajaokuta'),
            array('id' => 471, 'state_id' => 22, 'lga_name' => 'Ankpa'),
            array('id' => 472, 'state_id' => 22, 'lga_name' => 'Bassa'),
            array('id' => 473, 'state_id' => 22, 'lga_name' => 'Dekina'),
            array('id' => 474, 'state_id' => 22, 'lga_name' => 'Ibaji'),
            array('id' => 475, 'state_id' => 22, 'lga_name' => 'Idah'),
            array('id' => 476, 'state_id' => 22, 'lga_name' => 'Igalamela Odolu'),
            array('id' => 477, 'state_id' => 22, 'lga_name' => 'Ijumu'),
            array('id' => 478, 'state_id' => 22, 'lga_name' => 'Kabba/Bunu'),
            array('id' => 479, 'state_id' => 22, 'lga_name' => 'Kogi'),
            array('id' => 480, 'state_id' => 22, 'lga_name' => 'Lokoja'),
            array('id' => 481, 'state_id' => 22, 'lga_name' => 'Mopa Muro'),
            array('id' => 482, 'state_id' => 22, 'lga_name' => 'Ofu'),
            array('id' => 483, 'state_id' => 22, 'lga_name' => 'Ogori/Magongo'),
            array('id' => 484, 'state_id' => 22, 'lga_name' => 'Okehi'),
            array('id' => 485, 'state_id' => 22, 'lga_name' => 'Okene'),
            array('id' => 486, 'state_id' => 22, 'lga_name' => 'Olamaboro'),
            array('id' => 487, 'state_id' => 22, 'lga_name' => 'Omala'),
            array('id' => 488, 'state_id' => 22, 'lga_name' => 'Yagba East'),
            array('id' => 489, 'state_id' => 22, 'lga_name' => 'Yagba West'),
            array('id' => 490, 'state_id' => 23, 'lga_name' => 'Asa'),
            array('id' => 491, 'state_id' => 23, 'lga_name' => 'Baruten'),
            array('id' => 492, 'state_id' => 23, 'lga_name' => 'Edu'),
            array('id' => 493, 'state_id' => 23, 'lga_name' => 'Ekiti, Kwara State'),
            array('id' => 494, 'state_id' => 23, 'lga_name' => 'Ifelodun'),
            array('id' => 495, 'state_id' => 23, 'lga_name' => 'Ilorin East'),
            array('id' => 496, 'state_id' => 23, 'lga_name' => 'Ilorin South'),
            array('id' => 497, 'state_id' => 23, 'lga_name' => 'Ilorin West'),
            array('id' => 498, 'state_id' => 23, 'lga_name' => 'Irepodun'),
            array('id' => 499, 'state_id' => 23, 'lga_name' => 'Isin'),
            array('id' => 500, 'state_id' => 23, 'lga_name' => 'Kaiama'),
            array('id' => 501, 'state_id' => 23, 'lga_name' => 'Moro'),
            array('id' => 502, 'state_id' => 23, 'lga_name' => 'Offa'),
            array('id' => 503, 'state_id' => 23, 'lga_name' => 'Oke Ero'),
            array('id' => 504, 'state_id' => 23, 'lga_name' => 'Oyun'),
            array('id' => 505, 'state_id' => 23, 'lga_name' => 'Pategi'),
            array('id' => 506, 'state_id' => 24, 'lga_name' => 'Agege'),
            array('id' => 507, 'state_id' => 24, 'lga_name' => 'Ajeromi-Ifelodun'),
            array('id' => 508, 'state_id' => 24, 'lga_name' => 'Alimosho'),
            array('id' => 509, 'state_id' => 24, 'lga_name' => 'Amuwo-Odofin'),
            array('id' => 510, 'state_id' => 24, 'lga_name' => 'Apapa'),
            array('id' => 511, 'state_id' => 24, 'lga_name' => 'Badagry'),
            array('id' => 512, 'state_id' => 24, 'lga_name' => 'Epe'),
            array('id' => 513, 'state_id' => 24, 'lga_name' => 'Eti Osa'),
            array('id' => 514, 'state_id' => 24, 'lga_name' => 'Ibeju-Lekki'),
            array('id' => 515, 'state_id' => 24, 'lga_name' => 'Ifako-Ijaiye'),
            array('id' => 516, 'state_id' => 24, 'lga_name' => 'Ikeja'),
            array('id' => 517, 'state_id' => 24, 'lga_name' => 'Ikorodu'),
            array('id' => 518, 'state_id' => 24, 'lga_name' => 'Kosofe'),
            array('id' => 519, 'state_id' => 24, 'lga_name' => 'Lagos Island'),
            array('id' => 520, 'state_id' => 24, 'lga_name' => 'Lagos Mainland'),
            array('id' => 521, 'state_id' => 24, 'lga_name' => 'Mushin'),
            array('id' => 522, 'state_id' => 24, 'lga_name' => 'Ojo'),
            array('id' => 523, 'state_id' => 24, 'lga_name' => 'Oshodi-Isolo'),
            array('id' => 524, 'state_id' => 24, 'lga_name' => 'Shomolu'),
            array('id' => 525, 'state_id' => 24, 'lga_name' => 'Surulere, Lagos State'),
            array('id' => 526, 'state_id' => 25, 'lga_name' => 'Akwanga'),
            array('id' => 527, 'state_id' => 25, 'lga_name' => 'Awe'),
            array('id' => 528, 'state_id' => 25, 'lga_name' => 'Doma'),
            array('id' => 529, 'state_id' => 25, 'lga_name' => 'Karu'),
            array('id' => 530, 'state_id' => 25, 'lga_name' => 'Keana'),
            array('id' => 531, 'state_id' => 25, 'lga_name' => 'Keffi'),
            array('id' => 532, 'state_id' => 25, 'lga_name' => 'Kokona'),
            array('id' => 533, 'state_id' => 25, 'lga_name' => 'Lafia'),
            array('id' => 534, 'state_id' => 25, 'lga_name' => 'Nasarawa'),
            array('id' => 535, 'state_id' => 25, 'lga_name' => 'Nasarawa Egon'),
            array('id' => 536, 'state_id' => 25, 'lga_name' => 'Obi'),
            array('id' => 537, 'state_id' => 25, 'lga_name' => 'Toto'),
            array('id' => 538, 'state_id' => 25, 'lga_name' => 'Wamba'),
            array('id' => 539, 'state_id' => 26, 'lga_name' => 'Agaie'),
            array('id' => 540, 'state_id' => 26, 'lga_name' => 'Agwara'),
            array('id' => 541, 'state_id' => 26, 'lga_name' => 'Bida'),
            array('id' => 542, 'state_id' => 26, 'lga_name' => 'Borgu'),
            array('id' => 543, 'state_id' => 26, 'lga_name' => 'Bosso'),
            array('id' => 544, 'state_id' => 26, 'lga_name' => 'Chanchaga'),
            array('id' => 545, 'state_id' => 26, 'lga_name' => 'Edati'),
            array('id' => 546, 'state_id' => 26, 'lga_name' => 'Gbako'),
            array('id' => 547, 'state_id' => 26, 'lga_name' => 'Gurara'),
            array('id' => 548, 'state_id' => 26, 'lga_name' => 'Katcha'),
            array('id' => 549, 'state_id' => 26, 'lga_name' => 'Kontagora'),
            array('id' => 550, 'state_id' => 26, 'lga_name' => 'Lapai'),
            array('id' => 551, 'state_id' => 26, 'lga_name' => 'Lavun'),
            array('id' => 552, 'state_id' => 26, 'lga_name' => 'Magama'),
            array('id' => 553, 'state_id' => 26, 'lga_name' => 'Mariga'),
            array('id' => 554, 'state_id' => 26, 'lga_name' => 'Mashegu'),
            array('id' => 555, 'state_id' => 26, 'lga_name' => 'Mokwa'),
            array('id' => 556, 'state_id' => 26, 'lga_name' => 'Moya'),
            array('id' => 557, 'state_id' => 26, 'lga_name' => 'Paikoro'),
            array('id' => 558, 'state_id' => 26, 'lga_name' => 'Rafi'),
            array('id' => 559, 'state_id' => 26, 'lga_name' => 'Rijau'),
            array('id' => 560, 'state_id' => 26, 'lga_name' => 'Shiroro'),
            array('id' => 561, 'state_id' => 26, 'lga_name' => 'Suleja'),
            array('id' => 562, 'state_id' => 26, 'lga_name' => 'Tafa'),
            array('id' => 563, 'state_id' => 26, 'lga_name' => 'Wushishi'),
            array('id' => 564, 'state_id' => 27, 'lga_name' => 'Abeokuta North'),
            array('id' => 565, 'state_id' => 27, 'lga_name' => 'Abeokuta South'),
            array('id' => 566, 'state_id' => 27, 'lga_name' => 'Ado-Odo/Ota'),
            array('id' => 567, 'state_id' => 27, 'lga_name' => 'Egbado North'),
            array('id' => 568, 'state_id' => 27, 'lga_name' => 'Egbado South'),
            array('id' => 569, 'state_id' => 27, 'lga_name' => 'Ewekoro'),
            array('id' => 570, 'state_id' => 27, 'lga_name' => 'Ifo'),
            array('id' => 571, 'state_id' => 27, 'lga_name' => 'Ijebu East'),
            array('id' => 572, 'state_id' => 27, 'lga_name' => 'Ijebu North'),
            array('id' => 573, 'state_id' => 27, 'lga_name' => 'Ijebu North East'),
            array('id' => 574, 'state_id' => 27, 'lga_name' => 'Ijebu Ode'),
            array('id' => 575, 'state_id' => 27, 'lga_name' => 'Ikenne'),
            array('id' => 576, 'state_id' => 27, 'lga_name' => 'Imeko Afon'),
            array('id' => 577, 'state_id' => 27, 'lga_name' => 'Ipokia'),
            array('id' => 578, 'state_id' => 27, 'lga_name' => 'Obafemi Owode'),
            array('id' => 579, 'state_id' => 27, 'lga_name' => 'Odeda'),
            array('id' => 580, 'state_id' => 27, 'lga_name' => 'Odogbolu'),
            array('id' => 581, 'state_id' => 27, 'lga_name' => 'Ogun Waterside'),
            array('id' => 582, 'state_id' => 27, 'lga_name' => 'Remo North'),
            array('id' => 583, 'state_id' => 27, 'lga_name' => 'Shagamu'),
            array('id' => 584, 'state_id' => 28, 'lga_name' => 'Akoko North-East'),
            array('id' => 585, 'state_id' => 28, 'lga_name' => 'Akoko North-West'),
            array('id' => 586, 'state_id' => 28, 'lga_name' => 'Akoko South-West'),
            array('id' => 587, 'state_id' => 28, 'lga_name' => 'Akoko South-East'),
            array('id' => 588, 'state_id' => 28, 'lga_name' => 'Akure North'),
            array('id' => 589, 'state_id' => 28, 'lga_name' => 'Akure South'),
            array('id' => 590, 'state_id' => 28, 'lga_name' => 'Ese Odo'),
            array('id' => 591, 'state_id' => 28, 'lga_name' => 'Idanre'),
            array('id' => 592, 'state_id' => 28, 'lga_name' => 'Ifedore'),
            array('id' => 593, 'state_id' => 28, 'lga_name' => 'Ilaje'),
            array('id' => 594, 'state_id' => 28, 'lga_name' => 'Ile Oluji/Okeigbo'),
            array('id' => 595, 'state_id' => 28, 'lga_name' => 'Irele'),
            array('id' => 596, 'state_id' => 28, 'lga_name' => 'Odigbo'),
            array('id' => 597, 'state_id' => 28, 'lga_name' => 'Okitipupa'),
            array('id' => 598, 'state_id' => 28, 'lga_name' => 'Ondo East'),
            array('id' => 599, 'state_id' => 28, 'lga_name' => 'Ondo West'),
            array('id' => 600, 'state_id' => 28, 'lga_name' => 'Ose'),
            array('id' => 601, 'state_id' => 28, 'lga_name' => 'Owo'),
            array('id' => 602, 'state_id' => 29, 'lga_name' => 'Atakunmosa East'),
            array('id' => 603, 'state_id' => 29, 'lga_name' => 'Atakunmosa West'),
            array('id' => 604, 'state_id' => 29, 'lga_name' => 'Aiyedaade'),
            array('id' => 605, 'state_id' => 29, 'lga_name' => 'Aiyedire'),
            array('id' => 606, 'state_id' => 29, 'lga_name' => 'Boluwaduro'),
            array('id' => 607, 'state_id' => 29, 'lga_name' => 'Boripe'),
            array('id' => 608, 'state_id' => 29, 'lga_name' => 'Ede North'),
            array('id' => 609, 'state_id' => 29, 'lga_name' => 'Ede South'),
            array('id' => 610, 'state_id' => 29, 'lga_name' => 'Ife Central'),
            array('id' => 611, 'state_id' => 29, 'lga_name' => 'Ife East'),
            array('id' => 612, 'state_id' => 29, 'lga_name' => 'Ife North'),
            array('id' => 613, 'state_id' => 29, 'lga_name' => 'Ife South'),
            array('id' => 614, 'state_id' => 29, 'lga_name' => 'Egbedore'),
            array('id' => 615, 'state_id' => 29, 'lga_name' => 'Ejigbo'),
            array('id' => 616, 'state_id' => 29, 'lga_name' => 'Ifedayo'),
            array('id' => 617, 'state_id' => 29, 'lga_name' => 'Ifelodun'),
            array('id' => 618, 'state_id' => 29, 'lga_name' => 'Ila'),
            array('id' => 619, 'state_id' => 29, 'lga_name' => 'Ilesa East'),
            array('id' => 620, 'state_id' => 29, 'lga_name' => 'Ilesa West'),
            array('id' => 621, 'state_id' => 29, 'lga_name' => 'Irepodun'),
            array('id' => 622, 'state_id' => 29, 'lga_name' => 'Irewole'),
            array('id' => 623, 'state_id' => 29, 'lga_name' => 'Isokan'),
            array('id' => 624, 'state_id' => 29, 'lga_name' => 'Iwo'),
            array('id' => 625, 'state_id' => 29, 'lga_name' => 'Obokun'),
            array('id' => 626, 'state_id' => 29, 'lga_name' => 'Odo Otin'),
            array('id' => 627, 'state_id' => 29, 'lga_name' => 'Ola Oluwa'),
            array('id' => 628, 'state_id' => 29, 'lga_name' => 'Olorunda'),
            array('id' => 629, 'state_id' => 29, 'lga_name' => 'Oriade'),
            array('id' => 630, 'state_id' => 29, 'lga_name' => 'Orolu'),
            array('id' => 631, 'state_id' => 29, 'lga_name' => 'Osogbo'),
            array('id' => 632, 'state_id' => 30, 'lga_name' => 'Afijio'),
            array('id' => 633, 'state_id' => 30, 'lga_name' => 'Akinyele'),
            array('id' => 634, 'state_id' => 30, 'lga_name' => 'Atiba'),
            array('id' => 635, 'state_id' => 30, 'lga_name' => 'Atisbo'),
            array('id' => 636, 'state_id' => 30, 'lga_name' => 'Egbeda'),
            array('id' => 637, 'state_id' => 30, 'lga_name' => 'Ibadan North'),
            array('id' => 638, 'state_id' => 30, 'lga_name' => 'Ibadan North-East'),
            array('id' => 639, 'state_id' => 30, 'lga_name' => 'Ibadan North-West'),
            array('id' => 640, 'state_id' => 30, 'lga_name' => 'Ibadan South-East'),
            array('id' => 641, 'state_id' => 30, 'lga_name' => 'Ibadan South-West'),
            array('id' => 642, 'state_id' => 30, 'lga_name' => 'Ibarapa Central'),
            array('id' => 643, 'state_id' => 30, 'lga_name' => 'Ibarapa East'),
            array('id' => 644, 'state_id' => 30, 'lga_name' => 'Ibarapa North'),
            array('id' => 645, 'state_id' => 30, 'lga_name' => 'Ido'),
            array('id' => 646, 'state_id' => 30, 'lga_name' => 'Irepo'),
            array('id' => 647, 'state_id' => 30, 'lga_name' => 'Iseyin'),
            array('id' => 648, 'state_id' => 30, 'lga_name' => 'Itesiwaju'),
            array('id' => 649, 'state_id' => 30, 'lga_name' => 'Iwajowa'),
            array('id' => 650, 'state_id' => 30, 'lga_name' => 'Kajola'),
            array('id' => 651, 'state_id' => 30, 'lga_name' => 'Lagelu'),
            array('id' => 652, 'state_id' => 30, 'lga_name' => 'Ogbomosho North'),
            array('id' => 653, 'state_id' => 30, 'lga_name' => 'Ogbomosho South'),
            array('id' => 654, 'state_id' => 30, 'lga_name' => 'Ogo Oluwa'),
            array('id' => 655, 'state_id' => 30, 'lga_name' => 'Olorunsogo'),
            array('id' => 656, 'state_id' => 30, 'lga_name' => 'Oluyole'),
            array('id' => 657, 'state_id' => 30, 'lga_name' => 'Ona Ara'),
            array('id' => 658, 'state_id' => 30, 'lga_name' => 'Orelope'),
            array('id' => 659, 'state_id' => 30, 'lga_name' => 'Ori Ire'),
            array('id' => 660, 'state_id' => 30, 'lga_name' => 'Oyo'),
            array('id' => 661, 'state_id' => 30, 'lga_name' => 'Oyo East'),
            array('id' => 662, 'state_id' => 30, 'lga_name' => 'Saki East'),
            array('id' => 663, 'state_id' => 30, 'lga_name' => 'Saki West'),
            array('id' => 664, 'state_id' => 30, 'lga_name' => 'Surulere, Oyo State'),
            array('id' => 665, 'state_id' => 31, 'lga_name' => 'Bokkos'),
            array('id' => 666, 'state_id' => 31, 'lga_name' => 'Barkin Ladi'),
            array('id' => 667, 'state_id' => 31, 'lga_name' => 'Bassa'),
            array('id' => 668, 'state_id' => 31, 'lga_name' => 'Jos East'),
            array('id' => 669, 'state_id' => 31, 'lga_name' => 'Jos North'),
            array('id' => 670, 'state_id' => 31, 'lga_name' => 'Jos South'),
            array('id' => 671, 'state_id' => 31, 'lga_name' => 'Kanam'),
            array('id' => 672, 'state_id' => 31, 'lga_name' => 'Kanke'),
            array('id' => 673, 'state_id' => 31, 'lga_name' => 'Langtang South'),
            array('id' => 674, 'state_id' => 31, 'lga_name' => 'Langtang North'),
            array('id' => 675, 'state_id' => 31, 'lga_name' => 'Mangu'),
            array('id' => 676, 'state_id' => 31, 'lga_name' => 'Mikang'),
            array('id' => 677, 'state_id' => 31, 'lga_name' => 'Pankshin'),
            array('id' => 678, 'state_id' => 31, 'lga_name' => 'Qua\'an Pan'),
            array('id' => 679, 'state_id' => 31, 'lga_name' => 'Riyom'),
            array('id' => 680, 'state_id' => 31, 'lga_name' => 'Shendam'),
            array('id' => 681, 'state_id' => 31, 'lga_name' => 'Wase'),
            array('id' => 682, 'state_id' => 32, 'lga_name' => 'Abua/Odual'),
            array('id' => 683, 'state_id' => 32, 'lga_name' => 'Ahoada East'),
            array('id' => 684, 'state_id' => 32, 'lga_name' => 'Ahoada West'),
            array('id' => 685, 'state_id' => 32, 'lga_name' => 'Akuku-Toru'),
            array('id' => 686, 'state_id' => 32, 'lga_name' => 'Andoni'),
            array('id' => 687, 'state_id' => 32, 'lga_name' => 'Asari-Toru'),
            array('id' => 688, 'state_id' => 32, 'lga_name' => 'Bonny'),
            array('id' => 689, 'state_id' => 32, 'lga_name' => 'Degema'),
            array('id' => 690, 'state_id' => 32, 'lga_name' => 'Eleme'),
            array('id' => 691, 'state_id' => 32, 'lga_name' => 'Emuoha'),
            array('id' => 692, 'state_id' => 32, 'lga_name' => 'Etche'),
            array('id' => 693, 'state_id' => 32, 'lga_name' => 'Gokana'),
            array('id' => 694, 'state_id' => 32, 'lga_name' => 'Ikwerre'),
            array('id' => 695, 'state_id' => 32, 'lga_name' => 'Khana'),
            array('id' => 696, 'state_id' => 32, 'lga_name' => 'Obio/Akpor'),
            array('id' => 697, 'state_id' => 32, 'lga_name' => 'Ogba/Egbema/Ndoni'),
            array('id' => 698, 'state_id' => 32, 'lga_name' => 'Ogu/Bolo'),
            array('id' => 699, 'state_id' => 32, 'lga_name' => 'Okrika'),
            array('id' => 700, 'state_id' => 32, 'lga_name' => 'Omuma'),
            array('id' => 701, 'state_id' => 32, 'lga_name' => 'Opobo/Nkoro'),
            array('id' => 702, 'state_id' => 32, 'lga_name' => 'Oyigbo'),
            array('id' => 703, 'state_id' => 32, 'lga_name' => 'Port Harcourt'),
            array('id' => 704, 'state_id' => 32, 'lga_name' => 'Tai'),
            array('id' => 705, 'state_id' => 33, 'lga_name' => 'Binji'),
            array('id' => 706, 'state_id' => 33, 'lga_name' => 'Bodinga'),
            array('id' => 707, 'state_id' => 33, 'lga_name' => 'Dange Shuni'),
            array('id' => 708, 'state_id' => 33, 'lga_name' => 'Gada'),
            array('id' => 709, 'state_id' => 33, 'lga_name' => 'Goronyo'),
            array('id' => 710, 'state_id' => 33, 'lga_name' => 'Gudu'),
            array('id' => 711, 'state_id' => 33, 'lga_name' => 'Gwadabawa'),
            array('id' => 712, 'state_id' => 33, 'lga_name' => 'Illela'),
            array('id' => 713, 'state_id' => 33, 'lga_name' => 'Isa'),
            array('id' => 714, 'state_id' => 33, 'lga_name' => 'Kebbe'),
            array('id' => 715, 'state_id' => 33, 'lga_name' => 'Kware'),
            array('id' => 716, 'state_id' => 33, 'lga_name' => 'Rabah'),
            array('id' => 717, 'state_id' => 33, 'lga_name' => 'Sabon Birni'),
            array('id' => 718, 'state_id' => 33, 'lga_name' => 'Shagari'),
            array('id' => 719, 'state_id' => 33, 'lga_name' => 'Silame'),
            array('id' => 720, 'state_id' => 33, 'lga_name' => 'Sokoto North'),
            array('id' => 721, 'state_id' => 33, 'lga_name' => 'Sokoto South'),
            array('id' => 722, 'state_id' => 33, 'lga_name' => 'Tambuwal'),
            array('id' => 723, 'state_id' => 33, 'lga_name' => 'Tangaza'),
            array('id' => 724, 'state_id' => 33, 'lga_name' => 'Tureta'),
            array('id' => 725, 'state_id' => 33, 'lga_name' => 'Wamako'),
            array('id' => 726, 'state_id' => 33, 'lga_name' => 'Wurno'),
            array('id' => 727, 'state_id' => 33, 'lga_name' => 'Yabo'),
            array('id' => 728, 'state_id' => 34, 'lga_name' => 'Ardo Kola'),
            array('id' => 729, 'state_id' => 34, 'lga_name' => 'Bali'),
            array('id' => 730, 'state_id' => 34, 'lga_name' => 'Donga'),
            array('id' => 731, 'state_id' => 34, 'lga_name' => 'Gashaka'),
            array('id' => 732, 'state_id' => 34, 'lga_name' => 'Gassol'),
            array('id' => 733, 'state_id' => 34, 'lga_name' => 'Ibi'),
            array('id' => 734, 'state_id' => 34, 'lga_name' => 'Jalingo'),
            array('id' => 735, 'state_id' => 34, 'lga_name' => 'Karim Lamido'),
            array('id' => 736, 'state_id' => 34, 'lga_name' => 'Kumi'),
            array('id' => 737, 'state_id' => 34, 'lga_name' => 'Lau'),
            array('id' => 738, 'state_id' => 34, 'lga_name' => 'Sardauna'),
            array('id' => 739, 'state_id' => 34, 'lga_name' => 'Takum'),
            array('id' => 740, 'state_id' => 34, 'lga_name' => 'Ussa'),
            array('id' => 741, 'state_id' => 34, 'lga_name' => 'Wukari'),
            array('id' => 742, 'state_id' => 34, 'lga_name' => 'Yorro'),
            array('id' => 743, 'state_id' => 34, 'lga_name' => 'Zing'),
            array('id' => 744, 'state_id' => 35, 'lga_name' => 'Bade'),
            array('id' => 745, 'state_id' => 35, 'lga_name' => 'Bursari'),
            array('id' => 746, 'state_id' => 35, 'lga_name' => 'Damaturu'),
            array('id' => 747, 'state_id' => 35, 'lga_name' => 'Fika'),
            array('id' => 748, 'state_id' => 35, 'lga_name' => 'Fune'),
            array('id' => 749, 'state_id' => 35, 'lga_name' => 'Geidam'),
            array('id' => 750, 'state_id' => 35, 'lga_name' => 'Gujba'),
            array('id' => 751, 'state_id' => 35, 'lga_name' => 'Gulani'),
            array('id' => 752, 'state_id' => 35, 'lga_name' => 'Jakusko'),
            array('id' => 753, 'state_id' => 35, 'lga_name' => 'Karasuwa'),
            array('id' => 754, 'state_id' => 35, 'lga_name' => 'Machina'),
            array('id' => 755, 'state_id' => 35, 'lga_name' => 'Nangere'),
            array('id' => 756, 'state_id' => 35, 'lga_name' => 'Nguru'),
            array('id' => 757, 'state_id' => 35, 'lga_name' => 'Potiskum'),
            array('id' => 758, 'state_id' => 35, 'lga_name' => 'Tarmuwa'),
            array('id' => 759, 'state_id' => 35, 'lga_name' => 'Yunusari'),
            array('id' => 760, 'state_id' => 35, 'lga_name' => 'Yusufari'),
            array('id' => 761, 'state_id' => 36, 'lga_name' => 'Anka'),
            array('id' => 762, 'state_id' => 36, 'lga_name' => 'Bakura'),
            array('id' => 763, 'state_id' => 36, 'lga_name' => 'Birnin Magaji/Kiyaw'),
            array('id' => 764, 'state_id' => 36, 'lga_name' => 'Bukkuyum'),
            array('id' => 765, 'state_id' => 36, 'lga_name' => 'Bungudu'),
            array('id' => 766, 'state_id' => 36, 'lga_name' => 'Gummi'),
            array('id' => 767, 'state_id' => 36, 'lga_name' => 'Gusau'),
            array('id' => 768, 'state_id' => 36, 'lga_name' => 'Kaura Namoda'),
            array('id' => 769, 'state_id' => 36, 'lga_name' => 'Maradun'),
            array('id' => 770, 'state_id' => 36, 'lga_name' => 'Maru'),
            array('id' => 771, 'state_id' => 36, 'lga_name' => 'Shinkafi'),
            array('id' => 772, 'state_id' => 36, 'lga_name' => 'Talata Mafara'),
            array('id' => 773, 'state_id' => 36, 'lga_name' => 'Chafe'),
            array('id' => 774, 'state_id' => 36, 'lga_name' => 'Zurmi')
        );
    }
}
